

title: Paul C. Scharf
description: >-
  Programmer, leader, mentor. Paul C. Scharf's personal hub and portfolio.
  See what I've been up to and how we could work together.
baseurl: ""
url: ""
permalink: /:categories/:year/:month/:day/:title